PythonVersion="3.8.6"
virtualEnvName="deploydjango"
compressedVirtualEnvFile="antenv.tar.gz"
OperationId="|Ik8h21viFdg=.d2ff1674_"
SourceDirectoryInBuildContainer="/tmp/8d8d4d115fe1ff6"
PlatformName="python"
CompressDestinationDir="false"
