# Generated by Django 3.1.2 on 2020-10-29 21:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aflevering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Nøgle')),
                ('niveau', models.IntegerField(default=1, verbose_name='Klassetrin for aflevering')),
                ('titel', models.CharField(default='Model af CoVID19', max_length=30, verbose_name='Afleveringens titel')),
                ('frist', models.DateField(default=datetime.date(2020, 11, 28), verbose_name='Afleveringsfrist')),
            ],
        ),
        migrations.CreateModel(
            name='Klasse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Nøgle')),
                ('skole', models.CharField(default='Frederiksborg Gymnasium og HF', max_length=70, verbose_name='Skolens navn')),
                ('navn', models.CharField(default='1a', max_length=10, verbose_name='Betegnelse')),
                ('start_år', models.IntegerField(default=2019, verbose_name='Startår')),
            ],
        ),
        migrations.CreateModel(
            name='Elev',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Nøgle')),
                ('fulde_navn', models.CharField(max_length=70, verbose_name='Fulde navn')),
                ('klasse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boxplot.klasse')),
            ],
        ),
        migrations.CreateModel(
            name='AssesmentScores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Nøgle')),
                ('opg1', models.IntegerField(verbose_name='Opg1')),
                ('opg2', models.IntegerField(verbose_name='Opg2')),
                ('opg3', models.IntegerField(verbose_name='Opg3')),
                ('opg4', models.IntegerField(verbose_name='Opg4')),
                ('opg5', models.IntegerField(verbose_name='Opg5')),
                ('opg6', models.IntegerField(verbose_name='Opg6')),
                ('tankegang', models.IntegerField(verbose_name='Tankegang')),
                ('fagsprog', models.IntegerField(verbose_name='Fagsprog')),
                ('cas', models.IntegerField(verbose_name='CAS-brug')),
                ('diagram', models.IntegerField(verbose_name='Grafer')),
                ('sammenhæng', models.IntegerField(verbose_name='Sammenhæng')),
                ('konklusion', models.IntegerField(verbose_name='Konklusion')),
                ('aflevering', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boxplot.aflevering')),
                ('elev', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boxplot.elev')),
            ],
        ),
        migrations.AddField(
            model_name='aflevering',
            name='klasse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boxplot.klasse'),
        ),
    ]
