# Generated by Django 3.1.2 on 2020-11-12 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxplot', '0002_auto_20201030_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='aflevering',
            name='oprettet',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Tid for oprettelse'),
        ),
        migrations.AddField(
            model_name='aflevering',
            name='senest',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Seneste ændring'),
        ),
        migrations.AddField(
            model_name='assesmentscores',
            name='oprettet',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Tid for oprettelse'),
        ),
        migrations.AddField(
            model_name='assesmentscores',
            name='senest',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Seneste ændring'),
        ),
        migrations.AddField(
            model_name='elev',
            name='oprettet',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Tid for oprettelse'),
        ),
        migrations.AddField(
            model_name='klasse',
            name='oprettet',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Tid for oprettelse'),
        ),
    ]
