# Generated by Django 3.1.2 on 2020-11-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxplot', '0003_auto_20201112_1756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssesmentScores',
            new_name='AssesmentScore',
        ),
    ]
